volumes:
  db_data:
    name: db_data
networks:
  coolify:
    external: true
services:
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - coolify
    ports:
      - "8001:8000"
    volumes:
      - ".:/var/www/html"
    healthcheck:
      test: curl --fail http://127.0.0.1:8000 || exit 1
      interval: 5s
      retries: 10
      timeout: 2s

    environment:
      PHP_FPM_POOL_NAME: "app"
      AUTORUN_ENABLED: "${AUTORUN_ENABLED}"
      APP_NAME: "${APP_NAME}"
      APP_ENV: "${APP_ENV}"
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "${APP_DEBUG}"
      APP_TIMEZONE: "${APP_TIMEZONE}"
      APP_URL: "${APP_URL}"
      APP_LOCALE: "${APP_LOCALE}"
      APP_FALLBACK_LOCALE: "${APP_FALLBACK_LOCALE}"
      APP_FAKER_LOCALE: "${APP_FAKER_LOCALE}"
      APP_MAINTENANCE_DRIVER: "${APP_MAINTENANCE_DRIVER}"
      BCRYPT_ROUNDS: "${BCRYPT_ROUNDS}"
      LOG_CHANNEL: "${LOG_CHANNEL}"
      LOG_STACK: "${LOG_STACK}"
      LOG_DEPRECATIONS_CHANNEL: "${LOG_DEPRECATIONS_CHANNEL}"
      LOG_LEVEL: "${LOG_LEVEL}"
      DB_CONNECTION: "${DB_CONNECTION}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      SESSION_DRIVER: "${SESSION_DRIVER}"
      SESSION_LIFETIME: "${SESSION_LIFETIME}"
      SESSION_ENCRYPT: "${SESSION_ENCRYPT}"
      SESSION_PATH: "${SESSION_PATH}"
      SESSION_DOMAIN: "${SESSION_DOMAIN}"
      BROADCAST_CONNECTION: "${BROADCAST_CONNECTION}"
      FILESYSTEM_DISK: "${FILESYSTEM_DISK}"
      QUEUE_CONNECTION: "${QUEUE_CONNECTION}"
      CACHE_STORE: "${CACHE_STORE}"
      CACHE_PREFIX: "${CACHE_PREFIX}"
      MAIL_MAILER: "${MAIL_MAILER}"
      MAIL_HOST: "${MAIL_HOST}"
      MAIL_PORT: "${MAIL_PORT}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      MAIL_ENCRYPTION: "${MAIL_ENCRYPTION}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS}"
      MAIL_FROM_NAME: "${MAIL_FROM_NAME}"
      VITE_APP_NAME: "${APP_NAME}"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - coolify
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "service mysqld status"]
      interval: 5s
      retries: 10
      timeout: 2s
