services:
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    volumes:
      - ".:/var/www/html"
    healthcheck:
      test: curl --fail http://0.0.0.0:8080 || exit 1
      interval: 10s
      retries: 10
      timeout: 2s

    environment:
      PORT: "8080"
      PHP_FPM_POOL_NAME: app
      AUTORUN_ENABLED: ${AUTORUN_ENABLED}
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_TIMEZONE: ${APP_TIMEZONE}
      APP_URL: ${APP_URL}
      ASSET_URL: ${ASSET_URL}
      APP_LOCALE: ${APP_LOCALE}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      VITE_APP_NAME: ${APP_NAME}
      SSL_MODE: ${SSL_MODE-full}
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
    name: db_data
    external: true
