networks:
    custom_network:
volumes:
    db_data:
        external: true
services:
    laravel_app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        networks:
            - custom_network
        depends_on:
            - db
    db:
        platform: "linux/amd64"
        image: mysql
        # Set max_allowed_packet to 256M (or any other value)
        command: --max_allowed_packet=32505856
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - custom_network
